on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
         
      - name: setup
        run: java pro_wrapper.java version

      - name: build
        run: |
          ./pro/bin/pro version
          ./pro/bin/pro
